<?xml version="1.0" encoding="utf-8"?><Database Name="School" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-26HSG19\SQLEXPRESS;Initial Catalog=School;Integrated Security=True" SettingsObjectName="lab_5.Properties.Settings" SettingsPropertyName="SchoolConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.students" Member="students">
    <Type Name="students">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Family" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>